Updated README and added CONTRIBUTING.md file
ARMmbed/mbed-os-example-blinky-baremetal pull request #43
Opened 2020-09-16 15:20 UTC by harmut01

## Summary of changes
Created CONTRIBUTING.md
Updated license information in README.md

## Impact of changes

None
## Migration actions required

None.
## Documentation

None.
## Pull request type

[x] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
[] Feature update (New feature / Functionality change / New API)
[] Major update (Breaking change E.g. Return code change / API behaviour change)

## Test results

[X] No Tests required for this change (E.g docs only update)
[] Covered by existing mbed-os tests (Greentea or Unittest)
[] Tests / results supplied as part of this PR
## Reviewers
@ARMmbed/mbed-os-core

2020-09-16 15:53 UTC, LDong-Arm commented on README.md
>  This project contains code from other projects. The original license text is included in those source files. They must comply with our license guide.
```suggestion
This project contains code from other projects. The original license text is included in those source files. They must comply with our [license guide](https://os.mbed.com/docs/mbed-os/latest/contributing/license.html)
```

2020-09-17 08:43 UTC, evedon requested changes
Please also add the license file

2020-09-17 10:45 UTC, LDong-Arm requested changes
~Need to add the actual LICENSE file~ Oh duplicated comment

2020-09-17 17:25 UTC, evedon approved these changes

2020-09-18 08:56 UTC, evedon commented
@LDong-Arm Your comment was addressed so are you happy to approve?

2020-09-18 09:00 UTC, LDong-Arm approved these changes

2020-09-18 09:05 UTC, evedon commented
@harmut01 Could you rebase your PR as this should remove the first commit?

2020-09-18 11:01 UTC, harmut01 commented
@evedon I have rebased the PR, this should address your comment.

2020-09-18 11:20 UTC, merged